apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: chaosagents.blackadder.io
spec:
  group: blackadder.io
  scope: Cluster  # a CRD can also be Namespaced
  names:
    plural: chaosagents
    singular: chaosagent
    kind: ChaosAgent
    shortNames:
    - ca
  versions:
  - name: v1alpha1  # you can serve multiple versions e.g v1beta2 or v1alpha1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              tantrumMode:
                type: boolean
              podTolerance:
                type: integer
    additionalPrinterColumns:
    - name: Tantrum
      type: boolean
      description: Kills Pods randomly
      jsonPath: .spec.tantrumMode
    - name: Tolerance
      type: integer
      description: Total number of Pod to tolerate before randomly killing Pods
      jsonPath: .spec.podTolerance
  - name: v1beta1  # you can serve multiple versions e.g v1beta2 or v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              tantrumMode:
                type: boolean
              podTolerance:
                type: integer
              cancerMode:
                type: boolean
              ipsumMode:
                type: boolean 
              eagerness:
                type: integer
                minimum: 1
                maximum: 100
              pauseDuration:
                type: integer
              excludedNamespaces:
                type: array
                items:
                  type: string           
    additionalPrinterColumns:
    - name: Tantrum
      type: boolean
      description: Kills Pods randomly
      jsonPath: .spec.tantrumMode
    - name: Tolerance
      type: integer
      description: Total number of Pod to tolerate before randomly killing Pods
      jsonPath: .spec.podTolerance
    - name: Cancer
      type: boolean
      jsonPath: .spec.cancerMode
      description: Scales deployments randomly
    - name: Ipsum
      jsonPath: .spec.impsumMode
      description: If active, it writes the content of ConfigMaps with random lorem ipsume strings.
      type: boolean
    - name: Eagerness
      type: number
      jsonPath: .spec.eagerness
      description: The probabilty of killing a Pod
    - name: Pause
      type: integer
      jsonPath: .spec.pauseDuration
      description: The pause in seconds after each cycle of actions
    - name: Excluded
      jsonPath: .spec.excludedNamespaces
      description: Which Namespace to exclude
      type: string
