---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: replica-checker-clusterrole
rules:
- apiGroups:
  - ""
  - "apps"
  resources:
  - "events"
  - "deployments"
  - "pods"
  - "namespaces"
  - "nodes"
  verbs:
  - get
  - list
  - watch
  - patch
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: replica-checker-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: replica-checker-clusterrole
subjects:
- kind: ServiceAccount
  name: replica-checker-sa
  namespace: replicachecker
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: replica-checker-sa
  namespace: replicachecker
