kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: delegator-operator
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "update", "patch"]
- apiGroups: ["istio.opso.info"]
  resources: ["delegators", "istiopolicymanagers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.istio.io"]
  resources: ["virtualservices", "sidecars", "authorizationpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["security.istio.io"]
  resources: ["authorizationpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] 
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: delegator-operator
roleRef:
  kind: ClusterRole
  name: delegator-operator
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: delegator-sa
  namespace: delegator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: delegator-sa
  namespace: delegator