apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pgdb-writers.writer.opso.io
spec:
  group: writer.opso.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              required: ["table", "name", "registered", "zipcode", "country"]
              properties:
                table:
                  type: string
                name:
                  type: string
                registered:
                  type: boolean
                zipcode:
                  type: integer
                country:
                  type: string
      additionalPrinterColumns:
      - name: Table
        type: string
        description: Table name to communicate
        jsonPath: .spec.table
      - name: Name
        type: string
        description: Name of the company to write into table
        jsonPath: .spec.name
      - name: Registered
        type: boolean
        description: Status of the company (registered or not) 
        jsonPath: .spec.registered
      - name: ZipCode
        type: integer
        description: Zip Code of the company 
        jsonPath: .spec.zipcode
      - name: Country
        type: string
        description: Country where located applied company 
        jsonPath: .spec.country
  scope: Namespaced
  names:
    plural: pgdb-writers
    singular: pgdb-writer
    kind: PgdbWriter
    shortNames:
    - pgdbw


    